### PR TITLE
Incoming webhook to upsert category publish via contentful

### PR DESCRIPTION
**Pull request by AndrewCowle**
## Changes in this PR

- Refactor API controllers to inherit from an API base controller (moved auth logic to base).
- Added auth URL (will probably extend on this later) clean way to test the auth on this method.
- Added API categories controller to accept payload from Contentful publish event.
- Allow all hosts in the development config (required when using `ngrok` for tunnelling webhooks to local machine.
- Added webhook doc.

## Next steps

- Consider versioning (namespace v1) API.
- Consider refactoring the auth logic used in specs to a concern.

### CODE REVIEW

**Comment by peterdavidhamilton** [comment]
Can you fill in the PR title and description please @AndrewCowle

**Comment by peterdavidhamilton** [comment]
Was what I pushed helpful? I wasn’t sure when I looked, what exactly you needed from me. Needs linting and some extra scenarios like a republished category and amended category.

**Comment by AndrewCowle** [comment]
> Was what I pushed helpful? I wasn’t sure when I looked, what exactly you needed from me. Needs linting and some extra scenarios like a republished category and amended category.

@peterdavidhamilton remember we spoke about this only inserts new categories on publish event - I have added a ticket to the backlog about updating categories :)

**Comment by peterdavidhamilton** [comment]
You go first @EdwinKruglov

**Review by EdwinKruglov — APPROVED** [review]

**Pull request merged**
