### PR TITLE
Find a Framework form refactor

### PR DESCRIPTION
**Pull request by peterdavidhamilton**
## Changes in this PR

- refactoring multi-step forms within Specify to address a number of bugs and lessen debt
- fix a bug caused by a FaF request not being submitted
- fix bug when guests swap to search for an org of a different type group vs. school
- fix missing org confirmation when editing
- refactor form logic for improved unit testing
- infer form values from the respondent, passed as a param
- tidy code in views, controllers and forms
- add missing coverage
- combine `school_urn` and `group_urn` into `org_id`, including reversible data migration

## Next steps

Continue refactor:

- create service to be single point of contact between Specify and Supported org data queries https://trello.com/c/Me3nKtOx/394-use-of-supported-gias-data-in-specify 
- common struct interface abstracting distinction between school and group

### CODE REVIEW

**Comment by peterdavidhamilton** [comment]
[Correct the navigation for searching for a school or group when editing a completed journey](https://trello.com/c/ITueNpme/426-correct-the-navigation-for-searching-for-a-school-or-group-when-editing-a-completed-journey)

**Comment by peterdavidhamilton** [comment]
[Specify support requests go to (FaF) procurement support instead of support-requests from the profile page](https://trello.com/c/3ynZjoVQ/396-specify-support-requests-go-to-faf-procurement-support-instead-of-support-requests-from-the-profile-page)

**Comment by peterdavidhamilton** [comment]
[Is this the school you're buying for? page; selecting the 'continue' button allows user to navigate to the next page without selecting an option](https://trello.com/c/s8PG8jLF/329-is-this-the-school-youre-buying-for-page-selecting-the-continue-button-allows-user-to-navigate-to-the-next-page-without-selectin)

**Review by d-a-v-e — APPROVED** [review]
This is such a large refactor I feel bad suggesting more work!

But the only thing I feel would improve it even further would be defining the positions with a dictionary that returns the position number. This would let the developer write things like 

```
position?(:message_body) && dsi_with_inferred_org? || position?(:email)
```

however, approved in it current state 👍

**Review by EdwinKruglov — APPROVED** [review]

**Pull request merged**
