### PR TITLE
[207] Create Case - select category (yes and no paths)

### PR DESCRIPTION
**Pull request by d-a-v-e**
## Changes in this PR

* moves category form section to new “request type” section
* JS for revealing category selection dropdown
* adds “not yet known” & “no applicable category” to db seed in `config/support/categories.yml`
* updates `create_case_form_schema.rb` to validate when no request_type is selected

## Resources
* [See #207 in Lucid spark for an overview of yes and no paths](https://lucid.app/lucidspark/07d0eab5-cbae-43ec-9bda-5f3f476d8bc2/edit?invitationId=inv_085d2727-f88f-4def-8d9d-4296850165b2#)
* [main trello ticket](https://trello.com/c/e9m5CQA3/286-207-on-create-a-case-allow-category-to-be-undefined)
 
## Screenshots of UI changes
Screenshot 2022-02-02 at 16 45 38
Screenshot 2022-02-02 at 16 45 43
Screenshot 2022-02-02 at 16 46 05

## next steps

- [x] add "please select" to categories
- [x] error on no selection
- [x] update specs
- [x] backfill all cases with a nil category to "Not applicable" category id.

### CODE REVIEW

**Comment by d-a-v-e** [comment]
[#207 create case journey (YES)](https://trello.com/c/lXJoWDBg/336-207-create-case-journey-yes)

**Comment by d-a-v-e** [comment]
[#207 create case journey (NO)](https://trello.com/c/1xmSuvHV/337-207-create-case-journey-no)

**Comment by shafiqahmedkhan** [comment]
LGTM!

**Comment by EdwinKruglov** [comment]
@d-a-v-e the code looks good. The only thing I noticed when going through the journey is that if I've selected a category and I go on to the CYA page, if I click `Change` and go back to the form, the `Request type` is set to `Yes`, but the drop-down is hidden.

**Review by EdwinKruglov — APPROVED** [review]

**Review by shafiqahmedkhan — APPROVED** [review]

**Comment by d-a-v-e** [comment]
> @d-a-v-e the code looks good. The only thing I noticed when going through the journey is that if I've selected a category and I go on to the CYA page, if I click `Change` and go back to the form, the `Request type` is set to `Yes`, but the drop-down is hidden.

@EdwinKruglov ahh great, spot, thanks. I'll push up a fix 🙌

**Pull request merged**
