### PR TITLE
Yard for improved documentation

### PR DESCRIPTION
**Pull request by PiperS52**
## Changes in this PR

- add missing flags to `.yardopts`
- remove `yard.rake` task 
- fix markdown table rendering

### CODE REVIEW

**Comment by PiperS52** [comment]
[Yard for improved documentation](https://trello.com/c/UcoGhvAi/839-yard-for-improved-documentation)

**Comment by peterdavidhamilton** [comment]
197 files... wow. You have ended up with generated docs in `/doc`

**Comment by peterdavidhamilton** [comment]
@PiperS52 you will need to clean up the compiled HTML files that have ended up in `/doc` rather than `/documentation`, we don't want these committed into the repo.

**Comment by PiperS52** [comment]
> @PiperS52 you will need to clean up the compiled HTML files that have ended up in `/doc` rather than `/documentation`, we don't want these committed into the repo.

It seems like this can be addressed by using the `output-dir PATH` flag when generating the docs with `yardoc` - I've added this to the readme.

**Comment by peterdavidhamilton** [comment]
> > @PiperS52 you will need to clean up the compiled HTML files that have ended up in `/doc` rather than `/documentation`, we don't want these committed into the repo.
> 
> It seems like this can be addressed by using the `output-dir PATH` flag when generating the docs with `yardoc` - I've added this to the readme.

That's in `.yardopts` already. We want the options file to control it so it's consistent for everyone.

**Comment by peterdavidhamilton** [comment]
Are we now documenting more than we need because `"app/**/*.rb", "lib/**/*.rb"` aren't set in the opts?

**Comment by peterdavidhamilton** [comment]
If you haven't tried `yard server` give it a go, would you benefit from that being in our docs?

**Comment by peterdavidhamilton** [comment]
Who are you going to get to review this PR?

**Comment by PiperS52** [comment]
> Are we now documenting more than we need because `"app/**/*.rb", "lib/**/*.rb"` aren't set in the opts?

Would you like me to add these two into the .yardopts file as well?

**Comment by PiperS52** [comment]
> Who are you going to get to review this PR?

I didn't request review as I think we may have originally said to leave this ticket/PR for a later date - would you like me to?

**Comment by peterdavidhamilton** [comment]
> > Who are you going to get to review this PR?
> 
> I didn't request review as I think we may have originally said to leave this ticket/PR for a later date - would you like me to?

When you think it's ready for review I think we should make sure it's off the board for next sprint.

**Comment by peterdavidhamilton** [comment]
> > Are we now documenting more than we need because `"app/**/*.rb", "lib/**/*.rb"` aren't set in the opts?
> 
> Would you like me to add these two into the .yardopts file as well?

Is there a need is what I'm asking. For example, is Ruby code from `/vendor` getting included, and would we also need `/config`?

**Comment by PiperS52** [comment]
> 

Adding these as flags within .yardopts does not seem to alter the number of files generated - so don't appear to be needed

**Comment by PiperS52** [comment]
> 

Adding "app/**/*.rb", "lib/**/*.rb", or (--exclude) "./vendor" and "./config" flags within .yardopts does not seem to alter the number of files generated - so don't appear to be needed

**Review by EdwinKruglov — APPROVED** [review]

**Review by peterdavidhamilton — APPROVED** [review]

**Pull request merged**
