### PR TITLE
[154] Correct Page CSS

### PR DESCRIPTION
**Pull request by d-a-v-e**
## Changes in this PR

* Removes bullet styling of lists for page sidebar
* reinstates timestamp styling

### Before

Screenshot 2021-12-03 at 14 08 08

### After
Screenshot 2021-12-03 at 14 07 16

### CODE REVIEW

**Comment by d-a-v-e** [comment]
[Correct Page CSS](https://trello.com/c/NjUQ5tEf/154-correct-page-css)

**Review by peterdavidhamilton — CHANGES_REQUESTED** [review]
Could we go for an `#id` and `@extend` using the specific style we need.
https://sass-lang.com/documentation/at-rules/extend
We only have one sidebar per page and this would defer to the front-end lib.

**Comment by d-a-v-e** [comment]
> Could we go for an `#id` and `@extend` using the specific style we need. https://sass-lang.com/documentation/at-rules/extend We only have one sidebar per page and this would defer to the front-end lib.

@peterdavidhamilton thanks, this looks better now. Have done the same for the timestamp as well.

**Review by EdwinKruglov — APPROVED** [review]

**Review by peterdavidhamilton — APPROVED** [review]
I think it would be good to eventually do away with the `specification` class and id because now we have markdown in multiple contexts. Good stuff. 👍🏼

**Pull request merged**
